// src/content/interpretation/nakshatras.js
// The 27 nakshatras — applied to the Moon (the mind) and the Lagna (the body).
//
// ⚠ AUTHORSHIP: Claude-authored from classical principles (BPHS, Brihat
// Samhita nakshatra svarupa, Muhurta Chintamani). Not reviewed by a practising
// astrologer — see the note in houses.js.
//
// Indexed 0–26 to match `getNakshatraInfo().index`.
//
// Pure data — Node-safe, no imports.

export const NAKSHATRAS = [
  { name: 'Ashwini', lord: 'Ketu', deity: 'Ashwini Kumaras', symbol: "a horse's head",
    beginner: 'Quick to start and quick to heal. You move first, recover fast, and rarely wait for permission.',
    practitioner: 'Ketu-ruled, kshipra (swift), deva gana. The physicians of the gods: speed, initiative and a healing faculty. Restlessness and impatience are the cost.' },
  { name: 'Bharani', lord: 'Venus', deity: 'Yama', symbol: 'the yoni',
    beginner: 'You carry things through — including hard things. Intense, capable of restraint, and drawn to extremes.',
    practitioner: 'Venus-ruled, ugra (fierce), manushya gana. Yama\'s star: bearing, restraint and the threshold between life and death. Creative force with a capacity for severity.' },
  { name: 'Krittika', lord: 'Sun', deity: 'Agni', symbol: 'a razor / flame',
    beginner: 'Sharp and purifying. You cut through pretence, sometimes before anyone asked you to.',
    practitioner: 'Sun-ruled, mishra (mixed), rakshasa gana. Agni\'s star: the flame that burns away impurity. Gives incisiveness, appetite, and a tongue that cuts.' },
  { name: 'Rohini', lord: 'Moon', deity: 'Brahma', symbol: 'an ox cart',
    beginner: 'Magnetic and grounded. Things grow around you, and people find you hard to leave.',
    practitioner: 'Moon-ruled, dhruva (fixed), manushya gana. The Moon\'s exaltation and its favourite wife: fertility, beauty, growth and material charm. Possessiveness is the shadow.' },
  { name: 'Mrigashira', lord: 'Mars', deity: 'Soma', symbol: "a deer's head",
    beginner: 'A seeker. You are always scenting after the next thing, and rarely satisfied when you find it.',
    practitioner: 'Mars-ruled, mridu (soft), deva gana. The searching deer: curiosity, gentleness and perpetual quest. Gives charm and a nervous, unsettled restlessness.' },
  { name: 'Ardra', lord: 'Rahu', deity: 'Rudra', symbol: 'a teardrop',
    beginner: 'Storm and clarity. You feel things hard, and what breaks in you tends to break open rather than apart.',
    practitioner: 'Rahu-ruled, tikshna (sharp), manushya gana. Rudra\'s star: the storm that clears the air. Emotional turbulence, penetrating intellect, transformation through grief.' },
  { name: 'Punarvasu', lord: 'Jupiter', deity: 'Aditi', symbol: 'a quiver of arrows',
    beginner: 'You return. Whatever knocks you down, you come back to yourself — usually wiser and rarely bitter.',
    practitioner: 'Jupiter-ruled, chara (movable), deva gana. Aditi\'s star — "return of the light": renewal, forgiveness, safe repetition. Gives resilience and a philosophical temperament.' },
  { name: 'Pushya', lord: 'Saturn', deity: 'Brihaspati', symbol: 'a cow\'s udder / flower',
    beginner: 'You nourish people. Steady, dutiful, and the one others come to when they need holding.',
    practitioner: 'Saturn-ruled, kshipra (swift), deva gana. Classically the most auspicious nakshatra: nourishment, dharma, priestly care. Conservative, dutiful, occasionally rigid.' },
  { name: 'Ashlesha', lord: 'Mercury', deity: 'the Nagas', symbol: 'a coiled serpent',
    beginner: 'You see through people. Penetrating, private, and capable of a coil-and-strike others don\'t see coming.',
    practitioner: 'Mercury-ruled, tikshna (sharp), rakshasa gana. The serpent\'s star: hypnotic insight, kundalini, and guile. Gives psychological penetration and a capacity for manipulation.' },
  { name: 'Magha', lord: 'Ketu', deity: 'the Pitris', symbol: 'a royal throne',
    beginner: 'You come from somewhere and you know it. Dignity, ancestry, and a natural claim to respect.',
    practitioner: 'Ketu-ruled, ugra (fierce), rakshasa gana. The throne of the ancestors: lineage, authority and inherited position. Pride, and obligation to the pitris.' },
  { name: 'Purva Phalguni', lord: 'Venus', deity: 'Bhaga', symbol: 'the front legs of a bed',
    beginner: 'You know how to enjoy yourself, and you make that contagious. Rest, romance, and creative play.',
    practitioner: 'Venus-ruled, ugra (fierce), manushya gana. Bhaga\'s star: pleasure, procreation, leisure and the arts. Indolence when the enjoyment becomes the whole point.' },
  { name: 'Uttara Phalguni', lord: 'Sun', deity: 'Aryaman', symbol: 'the back legs of a bed',
    beginner: 'You keep your word. Generous, reliable, and better in friendship than in solitude.',
    practitioner: 'Sun-ruled, dhruva (fixed), manushya gana. Aryaman\'s star: patronage, contracts, honourable partnership. Gives dependability and a need to be needed.' },
  { name: 'Hasta', lord: 'Moon', deity: 'Savitar', symbol: 'an open hand',
    beginner: 'Whatever you put your hands to works. Skilful, clever, and quietly able to get what you want.',
    practitioner: 'Moon-ruled, kshipra (swift), deva gana. Savitar\'s hand: craft, dexterity, healing and sleight. Gives manual and mental skill, and a talent for acquisition.' },
  { name: 'Chitra', lord: 'Mars', deity: 'Tvashtar', symbol: 'a bright jewel',
    beginner: 'You make beautiful things and you like to be looked at. An eye for design that is unusually exact.',
    practitioner: 'Mars-ruled, mridu (soft), rakshasa gana. Tvashtar the celestial architect: design, illusion, brilliance. Gives aesthetic precision and a taste for display.' },
  { name: 'Swati', lord: 'Rahu', deity: 'Vayu', symbol: 'a blade of grass in wind',
    beginner: 'Independent to the bone. You bend rather than break, and you do not like being held.',
    practitioner: 'Rahu-ruled, chara (movable), deva gana. Vayu\'s star: autonomy, trade, flexibility, scattered movement. Gives diplomacy and a resistance to being tied down.' },
  { name: 'Vishakha', lord: 'Jupiter', deity: 'Indra-Agni', symbol: 'a triumphal arch',
    beginner: 'Goal-driven and patient about it. You will wait years for the thing you decided on.',
    practitioner: 'Jupiter-ruled, mishra (mixed), rakshasa gana. Indragni\'s star: focused ambition, delayed then decisive success. Gives determination and a jealous streak.' },
  { name: 'Anuradha', lord: 'Saturn', deity: 'Mitra', symbol: 'a lotus / staff',
    beginner: 'You make friends and keep them. Devotion, and the ability to thrive far from home.',
    practitioner: 'Saturn-ruled, mridu (soft), deva gana. Mitra\'s star: friendship, devotion, success abroad. The one nakshatra where Saturn gives warmth; gives loyalty and organising power.' },
  { name: 'Jyeshtha', lord: 'Mercury', deity: 'Indra', symbol: 'an earring / umbrella',
    beginner: 'The eldest, whether or not you were born first. Protective, proud, and carrying more than you show.',
    practitioner: 'Mercury-ruled, tikshna (sharp), rakshasa gana. Indra\'s star: seniority, protection, occult power and its burdens. Gives authority, isolation and a defensive pride.' },
  { name: 'Mula', lord: 'Ketu', deity: 'Nirriti', symbol: 'a bunch of tied roots',
    beginner: 'You go to the root of things, and you are willing to tear something up to get there.',
    practitioner: 'Ketu-ruled, tikshna (sharp), rakshasa gana. Nirriti\'s star at the galactic centre: investigation, destruction that precedes truth, gandanta. Gives radical inquiry and upheaval.' },
  { name: 'Purva Ashadha', lord: 'Venus', deity: 'Apas', symbol: 'a winnowing basket',
    beginner: 'Unbeatable optimism. You are hard to discourage and harder to argue down.',
    practitioner: 'Venus-ruled, ugra (fierce), manushya gana. The waters\' star: invincibility, purification, persuasion. Gives conviction, popularity and obstinacy.' },
  { name: 'Uttara Ashadha', lord: 'Sun', deity: 'the Vishvadevas', symbol: 'an elephant tusk',
    beginner: 'You win by not giving up. Late, durable, entirely earned success.',
    practitioner: 'Sun-ruled, dhruva (fixed), manushya gana. The universal gods: permanent victory, integrity, leadership that lasts. Gives principle and slow, unshakeable advance.' },
  { name: 'Shravana', lord: 'Moon', deity: 'Vishnu', symbol: 'an ear / three footprints',
    beginner: 'You listen better than most people talk. Learning comes through hearing and through people.',
    practitioner: 'Moon-ruled, chara (movable), deva gana. Vishnu\'s star: hearing, tradition, scholarship, connection. Gives receptivity and a scholar\'s memory.' },
  { name: 'Dhanishta', lord: 'Mars', deity: 'the Vasus', symbol: 'a drum',
    beginner: 'Rhythm and wealth. You keep time for other people and prosper doing it.',
    practitioner: 'Mars-ruled, chara (movable), rakshasa gana. The Vasus\' drum: music, timing, prosperity, group leadership. Gives abundance and a certain hardness.' },
  { name: 'Shatabhisha', lord: 'Rahu', deity: 'Varuna', symbol: 'an empty circle',
    beginner: 'A hundred healers and one loner. You are drawn to what is secret, and you keep your own counsel.',
    practitioner: 'Rahu-ruled, chara (movable), rakshasa gana. Varuna\'s star: healing, secrecy, reclusion, the veil. Gives medical or mystical faculty and profound privacy.' },
  { name: 'Purva Bhadrapada', lord: 'Jupiter', deity: 'Aja Ekapada', symbol: 'a two-faced man / sword',
    beginner: 'Intense and a little otherworldly. You see the far edge of things and are not entirely comfortable here.',
    practitioner: 'Jupiter-ruled, ugra (fierce), manushya gana. The one-footed goat: asceticism, fire, penetrating vision, extremity. Gives mystical intensity and detachment from the ordinary.' },
  { name: 'Uttara Bhadrapada', lord: 'Saturn', deity: 'Ahir Budhnya', symbol: 'the back of a funeral cot',
    beginner: 'Deep stillness. You carry a calm that other people rest on without being told.',
    practitioner: 'Saturn-ruled, dhruva (fixed), manushya gana. The serpent of the deep: wisdom, endurance, depth, kundalini at rest. Gives gravity, restraint and genuine peace.' },
  { name: 'Revati', lord: 'Mercury', deity: 'Pushan', symbol: 'a fish / drum',
    beginner: 'Kind, and a natural guide for others. You get people home, even when you are lost yourself.',
    practitioner: 'Mercury-ruled, mridu (soft), deva gana. Pushan the shepherd: safe passage, nourishment, compassion, completion. The last star — gives gentleness and a sense of ending.' },
]
