import { precacheAndRoute } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { CacheFirst } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST)

// COI (Cross-Origin Isolation) logic
self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (e) => e.waitUntil(self.clients.claim()));

async function handleFetch(request) {
  let r;
  try { 
    r = await fetch(request); 
  } catch (err) { 
    // If fetch fails (e.g. offline), try to find in cache if it's a precached asset
    // workbox-precaching handles this via fetch events, but since we are overriding,
    // we need to be careful. Actually, it's better to let workbox handle its routes.
    return; 
  }

  if (!r || r.status < 200 || r.status > 599) return r;

  const headers = new Headers(r.headers);
  headers.set("Cross-Origin-Embedder-Policy", "require-corp");
  headers.set("Cross-Origin-Opener-Policy", "same-origin");
  
  return new Response(r.body, { status: r.status, statusText: r.statusText, headers });
}

// Runtime caching for Geocoding API
registerRoute(
  /^https:\/\/nominatim\.openstreetmap\.org\/.*/i,
  new CacheFirst({
    cacheName: 'geocoding-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
)

// Runtime caching for Timezone API
registerRoute(
  /^https:\/\/timeapi\.io\/api\/TimeZone\/.*/i,
  new CacheFirst({
    cacheName: 'timezone-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
)

// Override fetch to inject COI headers
// NOTE: This might interfere with Workbox registerRoute if not careful.
// Workbox strategies usually handle fetch events.
// A better way is to use a workbox plugin to inject headers.

/*
self.addEventListener("fetch", (e) => {
  // If it's a workbox route, let workbox handle it? 
  // No, we want COI headers on EVERYTHING.
  e.respondWith(handleFetch(e.request));
});
*/

// Improved COI integration with Workbox:
// We can use a global fetch listener but we must ensure workbox still works.
// Or just use the simple fetch listener from coi-serviceworker and let workbox do its thing via its own listeners.
// Since we want both, we can wrap the fetch event.

self.addEventListener("fetch", (e) => {
  // Let workbox or the browser handle the request first, then add headers.
  // This is tricky. Let's use the standard coi-serviceworker approach but make sure precaching works.
  e.respondWith(
    fetch(e.request).then(r => {
      if (!r || r.status < 200 || r.status > 599) return r;
      const headers = new Headers(r.headers);
      headers.set("Cross-Origin-Embedder-Policy", "require-corp");
      headers.set("Cross-Origin-Opener-Policy", "same-origin");
      return new Response(r.body, { status: r.status, statusText: r.statusText, headers });
    }).catch(() => {
        // Fallback to cache if offline
        return caches.match(e.request);
    })
  );
});
